name: Run units tests

on:
  push:
    branches:
      - master
      - develop
    tags:
      - '**'
  pull_request:

jobs:
  build:
    name: build on ${{ matrix.platform || matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu
          - macos
          - windows
        python-version:
          - '3.6'
          - '3.7'
          - '3.8'
          - '3.9'
        wheels-dir:
          - '.wheels'
        include:
          - os: ubuntu
            platform: linux
          - os: windows
            ls: dir

    runs-on: ${{ format('{0}-latest', matrix.os) }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install cffi and virtualenv
        run: pip install cffi virtualenv
      - name: Install RUST toolchain
        uses: actions-rs/toolchain@v1
        id: rustup
        with:
          profile: minimal
          toolchain: nightly
          override: true
#      - name: Install bindings
#        run: |
#          pip install maturin
#          maturin develop
#      - name: Test with pytest
#        run: |
#          pip install pytest
#          pytest tests.py
      - name: Create wheels dir
        run: |
          mkdir ${{ matrix.wheels-dir }}
      - name: Build ${{ matrix.platform || matrix.os }} binaries
        run: |
          pip install maturin
          maturin build -o ${{ matrix.wheels-dir }}

      - name: list wheels
        run: ${{ matrix.ls || 'ls -lh' }} ${{ matrix.wheels-dir }}

      - name: twine check
        run: |
          pip install -U twine
          twine check ${{ matrix.wheels-dir }}/*
      - name: Upload to github releases
        if: startsWith(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.wheels-dir }}/*
          file_glob: true
          tag: ${{ github.ref }}

